open Token

let pp_token = function
  | ADD -> "ADD"
  | MULT -> "MULT"
  | INT i -> Printf.sprintf "INT(%d)" i
  | EOF -> "EOF"
  | FUNC -> "FUNC"
  | STRUCT -> "STRUCT"
  | ID s -> Printf.sprintf "ID(%s)" s
  | LBRAC -> "LBRAC"
  | RBRAC -> "RBRAC"
  | RPAREN -> "RPAREN"
  | LPAREN -> "LPAREN"
  | PRINTF -> "PRINTF"
  | STRING s -> Printf.sprintf "STRING(%s)" s
  | COMMA -> "COMMA"
  | SEMICOLON -> "SEMICOLON"
  | COLON -> "COLON"
  | AMPERSAND -> "AMPERSAND"
  | STR -> "TYPE STR"
  | STATIC -> "STATIC"
  | EQUALS -> "EQUALS"
  | ISEQUAL -> "ISEQUALS"
  | PERIOD -> "PERIOD"
  | SUB -> "SUB"
  | DIV -> "DIV"
  | MOD -> "MOD"
  | LT -> "LT"
  | GT -> "GT"
  | LTE -> "LTE"
  | GTE -> "GTE"
  | NEQ -> "NEQ"
  | AND -> "AND"
  | OR -> "OR"
  | NOT -> "NOT"
  | BAND -> "BAND"
  | BOR -> "BOR"
  | XOR -> "XOR"
  | BNOT -> "BNOT"
  | LSHIFT -> "LSHIFT"
  | RSHIFT -> "RSHIFT"
  | PLUSEQ -> "PLUSEQ"
  | MINUSEQ -> "MINUSEQ"
  | MULTEQ -> "MULTEQ"
  | DIVEQ -> "DIVEQ"
  | MODEQ -> "MODEQ"
  | BANDEQ -> "BANDEQ"
  | BOREQ -> "BOREQ"
  | XOREQ -> "XOREQ"
  | LSHIFTEQ -> "LSHIFTEQ"
  | RSHIFTEQ -> "RSHIFTEQ"
  | TRUE -> "TRUE"
  | FALSE -> "FALSE"
  | LET -> "LET"
  | I32 -> "I32"
